[net]
git-fetch-with-cli = true

[patch."https://github.com/openvm-org/stark-backend.git"]
openvm-stark-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }
openvm-stark-sdk = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }
openvm-codec-derive = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }
openvm-cpu-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }
openvm-cuda-builder = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }
openvm-cuda-common = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }
openvm-cuda-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "41d12cc0b3c4733c89a476ee33b15e7e66fd5ce8" }

[patch."https://github.com/openvm-org/openvm.git"]
# OpenVM core
openvm = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
# TODO: add back
# openvm-benchmarks-prove = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-build = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-circuit-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-circuit-primitives = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-circuit-primitives-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-continuations = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-custom-insn = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-instructions = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-instructions-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-macros-common = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-mod-circuit-builder = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-platform = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-poseidon2-air = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-recursion-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-recursion-circuit-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sdk = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sdk-config = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-verify-stark-host = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }

# Extensions
openvm-algebra-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-algebra-complex-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-algebra-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-algebra-moduli-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-algebra-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-bigint-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-bigint-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-bigint-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-deferral-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-deferral-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-deferral-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-ecc-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-ecc-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-ecc-sw-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-ecc-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-keccak256-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-keccak256-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-keccak256-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-pairing-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-pairing-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-pairing-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-rv32-adapters = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-rv32im-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-rv32im-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-rv32im-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sha2-air = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sha2-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sha2-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sha2-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }

# Guest libs
k256 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
p256 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-keccak256 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-pairing = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }
openvm-sha2 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "6a2696a6a0c59f4aa6422c69eab1250764b5e211" }

# [patch.crates-io]
# revm = { path = "../revm/crates/revm" }
# revm-primitives = { path = "../revm/crates/primitives" }
# revm-interpreter = { path = "../revm/crates/interpreter" }
# revm-precompile = { path = "../revm/crates/precompile" }
