[net]
git-fetch-with-cli = true

[patch."https://github.com/openvm-org/stark-backend.git"]
openvm-stark-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }
openvm-stark-sdk = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }
openvm-codec-derive = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }
openvm-cpu-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }
openvm-cuda-builder = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }
openvm-cuda-common = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }
openvm-cuda-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", rev = "8f23bfc4b209869aab8cd57ac0100f3bd0277c6b" }

[patch."https://github.com/openvm-org/openvm.git"]
# OpenVM core
openvm = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
# TODO: add back
# openvm-benchmarks-prove = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-build = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-circuit-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-circuit-primitives = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-circuit-primitives-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-continuations = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-custom-insn = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-instructions = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-instructions-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-macros-common = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-mod-circuit-builder = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-platform = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-poseidon2-air = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-recursion-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-recursion-circuit-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sdk = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sdk-config = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-verify-stark-host = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }

# Extensions
openvm-algebra-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-algebra-complex-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-algebra-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-algebra-moduli-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-algebra-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-bigint-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-bigint-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-bigint-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-deferral-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-deferral-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-deferral-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-ecc-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-ecc-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-ecc-sw-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-ecc-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-keccak256-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-keccak256-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-keccak256-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-pairing-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-pairing-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-pairing-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-riscv-adapters = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-riscv-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-riscv-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-riscv-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sha2-air = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sha2-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sha2-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sha2-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }

# Guest libs
k256 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
p256 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-keccak256 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-pairing = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }
openvm-sha2 = { git = "ssh://git@github.com/openvm-org/openvm.git", rev = "88a1eb39b25e02fbb30bd08d0ba69170ab11dc57" }

# [patch.crates-io]
# revm = { path = "../revm/crates/revm" }
# revm-primitives = { path = "../revm/crates/primitives" }
# revm-interpreter = { path = "../revm/crates/interpreter" }
# revm-precompile = { path = "../revm/crates/precompile" }
